### ISSUE TITLE
Astron on windows server 2008?

### ISSUE THREAD

**Issue by mgracer48** [Astron/Astron#315]
Basically, it says it only supports Visual Studio 2013. So how do I build on Windows Server? Visual studio 2013 said it wasn't compatible when I tried download.

**Comment by kestred** [comment]
According to the Microsoft website, Windows Server 2008 does support Visual Studio 2013.
Astron is not the appropriate place to look for support setting up Visual Studio; please use [Microsoft's forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?category=visualstudio) for support with Microsoft products.

Astron doesn't need to be compiled on the server; you may compile it on your local machine and copy the executable to the server.  If this doesn't work; please don't create an Astron issue, because I don't know how to support Microsoft system incompatibilities.

### Important Note
Astron **ONLY** supports compiling on Windows for Development purposes.
It is highly recommended you use a Linux based server to run the Astron daemon (best support for Ubuntu/Debian variants; other distros should work fine for an intelligent developer; you may also have luck with other Unix variants like OpenBSD).
