### ISSUE TITLE
Kernel-mode message director

### ISSUE THREAD

**Issue by CFSworks** [Astron/Astron#331]
In the same vane as projects like [kHTTPd](http://www.fenrus.demon.nl/) and [kdbus](https://lwn.net/Articles/580194/), which achieve better performance for their respective tasks (HTTP daemon and D-Bus daemon) by moving the code into kernelspace, we'd like to move the Astron message director into kernelspace. Doing so has any number of advantages:

- The kernel can uninterruptably execute code.
- The MD implementation can rely directly on the TCP implementation in the kernel without having to deal with the overhead of a syscall.
- Many Astron daemons on the same system can communicate without passing through the networking stack.

To do this, we'd have to achieve the following:
- [ ] Remove hard dependencies from the MD on the networking stack.
- [ ] Implementation of C++ for kernelspace code.
- [ ] Abstraction layer for Astron MD participants to support kernel calls instead of local enqueue operations.
- [ ] Allocation of syscalls/ioctls for MD operations. If we go with ioctls, we'd also need an entry in /dev to reach the kernel-mode MD ("/dev/astron"?)

We would like to support Linux at a minimum. Other UNIX flavors are welcome. For Windows, we may stick to the old, legacy user-space message director, as the overhead of getting a driver signed with Microsoft may not prove to be worth it.

**Comment by jjkoletar** [comment]
@CFSworks Skimming resources on writing kernel code (though most are focused on writing code to be submitted to *the* kernel, rather than just running your own code as a kernel module for fun and profit), it seems like there are [cautions against running C++ kernel modules](http://www.tux.org/lkml/#s15-3). Any thoughts?

**Comment by xHarv14** [comment]
I'm fine with leaving the old MD code in for Windows. We only really support Windows a 'development' environment, rather than a production environment. This type of optimization is for production anyways. My only concern is the reliability when running dev vs prod. tests for certain developers/projects.

**Comment by bobbybee** [comment]
I for one think writing an MD as an EFI application could prove totally interesting (and useless) :smile:

**Comment by loblao** [comment]
Based on OP date I must ask. Is this [serious](http://en.wikipedia.org/wiki/April_Fools%27_Day)?
