### ISSUE TITLE
Astron 32 bit  buildet request

### ISSUE THREAD

**Issue by Starlow88** [Astron/Astron#334]
Can somebody please give me Astron 32 bit build?

**Comment by starsky135** [comment]
That's not an issue.

**Comment by jjkoletar** [comment]
Instructions for compiling Astron are located [here](https://github.com/Astron/Astron/tree/master/docs/building). We do not provide pre-built binaries of Astron, simply because the project is still in its infancy, and has yet to have an official tagged release.

Additionally, GitHub issues are not a place for support. Feel free to ask around for help in #Astron on Freenode, however, note that we're all volunteers and can't always give you tons of assistance. We'll be happy to try our best, though!
