### ISSUE TITLE
Astron and saving strings

### ISSUE THREAD

**Issue by greendiesel47** [Astron/Astron#338]
i built astron in debug mode on visual studio 2013 and when i go to save a string to the database i have setup it comes out like this:

```
ACCOUNT_ID: "['d', 'e', 'v']"
```

It is only with strings, not with integers.

**Comment by AlJaMa** [comment]
Hello @greendiesel47,

Github is not a place for support. This does not appear to be an issue with Astron. 
To chat about this, please feel free to join us at #astron on freenode.

Also, I feel this may apply. https://github.com/Astron/Astron/wiki/Not-Toontown

**Comment by bobbybee** [comment]
@AlJaMa I've seen a version of this before, but I'm not sure if this was a bug in Astron's database backend or at the application (client or AI) level.  I'm not reopening the issue until we know it is, in fact, and issue, but I will unlock it--- @loblao mentioned he's also seen something like this. 

It might be shadowing a larger bug, so it's better not to dismiss it immediately :smile:

**Comment by xHarv14** [comment]
Purely based on the original issue, it would seem that something is taking the string and splitting it into a list before passing it to Astron. As seen above, the ACCOUNT_ID is still in fact a string, except something took the string, split it and then passed the pythonic __repr__ of that list as a string. To me, this looks like a pythonic application error rather than an Astron error, and was correctly labelled as invalid by @AlJaMa above.

**Comment by bobbybee** [comment]
@xHarv14 That still doesn't rule out the possibility of this being a bug in Astron/panda3d, which granted is still not on-topic here, but might be in our control to fix.

**Comment by xHarv14** [comment]
@bobbybee If it's an Astron/Panda3D bug, then the issue should be created in the relevant repo. For now, I'll close this and lock it again. If it does arise again, especially if it's from someone who using using the Astron-forked version of Panda3D, then we can re-open this.
