### ISSUE TITLE
"Ejecting Client <108>: Message type 24 not allowed prior to authentiation"

### ISSUE THREAD

**Issue by DauntlessTT** [Astron/Astron#357]
Hello, I have been recently been working on a Toontown project using the Astron network with an obsolete version of Panda3D to be specific, Panda-1.3.2. I have rewritten the Otpclientrepository to be compatible with Astron and all of the necessary server connection files as well. When I start my client, astron gives me the message "Ejecting Client <108>: Message type 24 not allowed prior to authentiation". I have tried to rework some of the files in panda but I have not yet been able to get around this issue. I would switch to a more modern version of Panda3D but for this project, I absolutely have to use a version of panda which supports python 2.4.1 or lower for many reasons. If there is any method to get around this, I would love some help. 

Thanks!

**Comment by loblao** [comment]
https://github.com/Astron/Astron/wiki/Not-Toontown

**Comment by mfwass** [comment]
Even though this isn't for Toontown support I want to put my two cents in here.

First, I'm thinking you're using 2.4.1 because that's the version of Python Disney used. I think you might be having trouble decompiling the bytecode from the game, so instead of decompiling the whole client you’re only modifying a few files that you need to. That version of Python is almost 11 years old and is safely able to be called obsolete.

Second, message type 24 is for ```CLIENT_OBJECT_UPDATE_FIELD```. Astron doesn’t support it, it is for CMU/OTP. You'll need to convert your client to use Astron, which is relatively trivial. You’d also need to convert Panda3D to use Astron, but I’m happy to say that the folks at Astron already have a [publicly available copy of Panda3D](https://github.com/Astron/panda3d) compatible with Astron. However, I doubt that compiling that version of Panda3D with Python 2.4 is trivial (if possible at all).

As a side note, there are many many Toontown servers out there. Developing a new server is a worthless effort at this point. Given that you're having issues even with these basic stuff, I highly recommend that you reconsider this, otherwise you may end up just wasting your time.
