### ISSUE TITLE
Error when building with macOs

### ISSUE THREAD

**Issue by Nickdoge** [Astron/Astron#385]
I tried to build Astron on a macbook running MacOs Sierra. 

At the end of it building i had this error:
http://pastebin.com/5dLraxqE

Thanks.

**Comment by mfwass** [comment]
Did you build Boost on your Macbook or did you download them precompiled?

**Comment by darktohka** [comment]
I downloaded them through list comprehension

**Comment by NickdogeDev** [comment]
I downloaded them precompiled with brew.

**Comment by mfwass** [comment]
Try reinstalling them.

**Comment by NickdogeDev** [comment]
I tried that and I had the same error.

**Comment by xHarv14** [comment]
Are you trying to build a 32-bit or 64-bit binary? And does your installation of boost match the target version?

**Comment by NickdogeDev** [comment]
Sorry for the late response, but I was using 64 bit.

**Comment by ashleyHutton** [comment]
I'm having this same issue, @NickdogeDev were you able to figure it out?

**Comment by staticfox** [comment]
So cmake is having a hard time finding the right openssl libraries to link against, for the time being, this should do the trick (yes it's a horrible hack, but sometimes you just want the thing to compile)

https://gist.github.com/staticfox/3602a2a2c2cdf4ef74ceb7d2d6ed5284

You don't have to remove `-Werror`, I just did it because it was bothering me. Also make sure that you're using that version of openssl from homebrew, otherwise change accordingly.
